development:
  adapter: sqlite3
  encoding: utf8
  database: database/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  encoding: utf8
  database: database/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  encoding: utf8
  database: database/production.sqlite3
  pool: 5
  timeout: 5000
